### ISSUE TITLE
X-ray transitions of Casino 2 intensities

### ISSUE THREAD

**Issue by ppinard** [drix00/pycasinotools#3]
Casino 2 returns X-ray intensities as K, L3 and M5 (see [Element.py](https://github.com/drix00/pycasinotools/blob/master/casinotools/fileformat/casino2/Element.py#L22)). To which X-ray transitions do these correspond? Is K all X-ray transitions having the K subshell as destination?

**Comment by drix00** [comment]
In CASINO 2, Ka1, La1, and Ma1 are the intended intensity to be calculated. However, the intensity is never multiply by the line weight factor. So the intensity calculated is the summation of  x-ray transitions with initial vacancy in the:

- K shell
- L3 shell
- M5 shell

Also no Coster-Kronig transition are not included in the calculation.

**Comment by ppinard** [comment]
If I understand correctly, to get the Fe Ll intensity, one would need to multiply the Casino L3 shell intensity by line weight factor of Fe Ll divided by the sum of line weights of La1, La2, Ll, Lt and Ls, as all these lines originate from the relaxation to the L3 subshell?

**Comment by drix00** [comment]
Yes, 
Ll is L3-M1, but the intensity returned (minus some constants) by casino is the ionization cross section for L3 subshell multiply by the fluorescence yield w_L3 (which include the all x-ray transition starting with L3) so to get Ll (L3-M1) you have to multiply by the weight = G_L3-M1 / Sum_S2 G_L3-S2. It is unfortunate that they separate the probability of emission in fluorescence yield and line weight, but most of the old models were separate like that.

**Comment by ppinard** [comment]
To confirm, the fluorescence yield is already included in the intensity returned by Casino?

What is S2 in Sum_S2 and G_L3-S2?

**Comment by drix00** [comment]
> To confirm, the fluorescence yield is already included in the intensity returned by Casino?

Yes

> What is S2 in Sum_S2 and G_L3-S2?

The final subshell, so you have to sum on all possible subshell.

**Comment by drix00** [comment]
This issue is resolved by solving issue #4.
