### ISSUE TITLE
Units of X-ray intensities

### ISSUE THREAD

**Issue by ppinard** [drix00/pycasinotools#4]
What are the units of Casino 2 X-ray intensities? 

The only information I found on this topic are two slides from Pierre Hovington's presentation at M&M2009:
![output-12](https://cloud.githubusercontent.com/assets/715280/23683135/4ae72ea6-038f-11e7-8a5e-18b973a671ec.png)
![output-13](https://cloud.githubusercontent.com/assets/715280/23683143/55213aba-038f-11e7-96f5-a4c55297b3ba.png)

Is this information valid? Is it possible to return an intensity without the hardcoded detector efficiency?

**Comment by drix00** [comment]
I think the slide forget some factor.
From the code:

- Solid angle of 0.0025 sr
- Current of 1 nA
- acquisition time of 1 s

The efficiency model in CASINO 2 is not good for modern EDS, i.e., Moxtek window. In the last version, the efficiency for each element can be modified by the user (idem for the MAC), but the information is not stored in the .cas file.

I have a project on bitbucket that give the CASINO 2 MAC and efficiency models:
https://bitbucket.org/hendrix_demers/pymassabsorptioncoefficienttools
in the file pymassabsorptioncoefficienttools.models.casino.py

The only difference between this code and CASINO 2 (before the next release) is I correct a bug with one of the MAC model, which affect low x-ray efficiency (< 1keV).

I propose to add the intensity (photon / e / sr) only in the .cas and not in the display, but pycasinotools will be able to read it. Could you confirm the unit and should I add the line weight or not?

**Comment by ppinard** [comment]
> Could you confirm the unit

The question is whether to include or not *steradian*. Casino, WinXray, NISTMonte, Monaco do not really have the concept of a detector area, as all X-rays are emitted towards a single point in space. What is the solid angle? NISTMonte seems to use 4pi and returns the intensity in photon / (sr electron).

> should I add the line weight or not?

I guess if the line weights are included, the question is which tabulation to use?

**Comment by drix00** [comment]
> he question is whether to include or not steradian. Casino, WinXray, NISTMonte, Monaco do not really have the concept of a detector area, as all X-rays are emitted towards a single point in space. What is the solid angle? NISTMonte seems to use 4pi and returns the intensity in photon / (sr electron).

In these program the steradian come from the ionization cross section that is isotropic in direction so it is divided by 4 pi and if you mix with bremsstrahlung intensity you need to have the same unit. To model the detector area, the intensity is multiplied by the solid angle of the detector. The unit of photon / electron / sr is useful to separate the effect of detector and dose versus resimulate all trajectories when you change one of these parameters. These programs does not simulate each discrete ionization event, but a emission probability along each trajectory segment with the current electron energy. 

> I guess if the line weights are included, the question is which tabulation to use?

For the line weight model, I would use winxray or mcxray model (I think they are the same).

**Comment by ppinard** [comment]
The goal is obviously have all X-ray intensities expressed in the same units regardless of the MC code. Based on your explanation, I think photon / (sr electron) is a good unit to use. 

If WinXRay and MCXray already have line weight included, I think it is best to do the same in Casino 2.

I think the option that the intensity in photon / (sr electron) (with the line weight for the major lines) is only available in *pycasinotools* is perfectly acceptable.

**Comment by drix00** [comment]
The commit  63cff5a add a new method which read the intensity in photon / (steradian electron) from the .cas file generated with version 2.50 and higher.
The method is `get_total_xray_intensities_1_esr` and work just like `getTotalXrayIntensities` as it only return the non zero intensity. A difference with `getTotalXrayIntensities`, `get_total_xray_intensities_1_esr` only return the emitted intensity. The intensity is a double `dict` of `intensities[z][line]`. The possible lines are listed in pycasinotools/casinotools/fileformat/casino2/line.py.

To test it you need to use this release of CASINO:
https://www.dropbox.com/s/l0if2tjngvqk9yc/2017-06-12_19h30m24s_CASINO_v2.5.0.0.zip?dl=0
After more testing this version will be available on CASINO website.
